In [3]:
import os
import time
import pandas as pd
import pubchempy as pcp
from tqdm import tqdm
from chembl_webresource_client.new_client import new_client

In [4]:
df = pd.read_csv("ctod_data.csv", low_memory=False)

# 2. Expand drug names from semi-colon list
df_expanded = df[['nct_id', 'drugs']].dropna()
df_expanded['drug_name'] = df_expanded['drugs'].astype(str).str.lower().str.split(';')
df_expanded = df_expanded.explode('drug_name')
df_expanded['drug_name'] = df_expanded['drug_name'].str.strip()
df_expanded = df_expanded[df_expanded['drug_name'].notna() & (df_expanded['drug_name'] != '')]

# 3. Filter to known drugs using ChEMBL
molecule = new_client.molecule
known_drugs = molecule.filter(max_phase__gte=1).only(['pref_name'])
known_drug_names = set(m['pref_name'].lower() for m in known_drugs if m['pref_name'])
df_expanded = df_expanded[df_expanded['drug_name'].isin(known_drug_names)]

# 4. Unique drug list
drug_names = df_expanded['drug_name'].dropna().unique()

In [5]:
# 5. Caching setup
CACHE_FILE = "partial_drug_info.csv"
if os.path.exists(CACHE_FILE):
    cached = pd.read_csv(CACHE_FILE)
    done = set(cached['drug_name'].dropna().str.lower())
    results = cached.to_dict('records')
    print(f"Loaded {len(done)} cached drugs")
else:
    results = []
    done = set()

mechanism = new_client.mechanism

In [6]:
# 6. Enrichment function
def get_drug_info(name):
    data = {'drug_name': name}

    # PubChem
    try:
        compound = pcp.get_compounds(name, 'name')[0]
        data['smiles'] = compound.canonical_smiles
        data['iupac'] = compound.iupac_name
        data['molecular_weight'] = compound.molecular_weight
        data['synonyms'] = "; ".join(compound.synonyms[:5]) if compound.synonyms else None
    except Exception as e:
        print(f"[PubChem fail] {name}: {e}")
        data['smiles'] = data['iupac'] = data['molecular_weight'] = data['synonyms'] = data['description'] = None

    # ChEMBL
    try:
        search = molecule.filter(pref_name__iexact=name)
        if not search:
            search = molecule.filter(molecule_synonyms__iexact=name)

        chembl_id = search[0]['molecule_chembl_id']
        mol = molecule.get(chembl_id)
        data['max_phase'] = mol.get('max_phase')
        data['drug_type'] = mol.get('molecule_type')

        mech = mechanism.filter(molecule_chembl_id=chembl_id)
        if mech:
            data['mechanism'] = mech[0].get('mechanism_of_action')
            data['target'] = mech[0].get('target_name')
        else:
            data['mechanism'] = data['target'] = None
    except Exception as e:
        print(f"[ChEMBL fail] {name}: {e}")
        data['max_phase'] = data['drug_type'] = data['mechanism'] = data['target'] = None

    time.sleep(0.5)  # Prevent rate limits
    return data

# 7. Loop with caching
for i, name in enumerate(tqdm(drug_names)):
    if name.lower() in done:
        continue
    info = get_drug_info(name)
    results.append(info)

    if len(results) % 100 == 0:
        pd.DataFrame(results).to_csv(CACHE_FILE, index=False)
        print(f"Saved batch at {len(results)} drugs")

# 8. Final save
drug_info_df = pd.DataFrame(results)
drug_info_df.to_csv("final_drug_info.csv", index=False)
print("Enrichment complete. Saved to final_drug_info.csv")

  0%|                                                                               | 1/2176 [00:02<1:36:38,  2.67s/it]

[PubChem fail] sargramostim: list index out of range

  1%|▍                                                                             | 11/2176 [00:27<1:32:23,  2.56s/it]

[PubChem fail] heparin: list index out of range

  1%|▍                                                                             | 12/2176 [00:29<1:23:33,  2.32s/it]

[PubChem fail] aflibercept: list index out of range

  1%|▋                                                                             | 20/2176 [00:48<1:29:45,  2.50s/it]

[PubChem fail] ipilimumab: list index out of range

  1%|▊                                                                             | 21/2176 [00:50<1:21:52,  2.28s/it]

[PubChem fail] tremelimumab: list index out of range

  2%|█▎                                                                            | 37/2176 [01:30<1:32:08,  2.58s/it]

[PubChem fail] pembrolizumab: list index out of range

  2%|█▎                                                                            | 38/2176 [01:32<1:22:28,  2.31s/it]

[PubChem fail] ranibizumab: list index out of range

  2%|█▌                                                                            | 43/2176 [01:43<1:25:07,  2.39s/it]

[PubChem fail] nivolumab: list index out of range

  3%|██▌                                                                           | 71/2176 [02:54<1:29:24,  2.55s/it]

[PubChem fail] parathyroid hormone: list index out of range

  4%|██▊                                                                           | 78/2176 [03:11<1:31:55,  2.63s/it]

[PubChem fail] trastuzumab: list index out of range

  4%|███▏                                                                          | 88/2176 [03:36<1:30:00,  2.59s/it]

[PubChem fail] vitamin b complex: list index out of range

  4%|███▍                                                                          | 95/2176 [03:53<1:26:40,  2.50s/it]

[PubChem fail] bevacizumab: list index out of range

  5%|███▌                                                                         | 100/2176 [04:05<1:27:42,  2.53s/it]

Saved batch at 100 drugs

  5%|███▋                                                                         | 104/2176 [04:15<1:25:57,  2.49s/it]

[PubChem fail] epratuzumab: list index out of range

  5%|███▉                                                                         | 111/2176 [04:33<1:30:47,  2.64s/it]

[PubChem fail] bavituximab: list index out of range

  6%|████▊                                                                        | 135/2176 [05:33<1:25:10,  2.50s/it]

[PubChem fail] margetuximab: list index out of range

  6%|████▉                                                                        | 141/2176 [05:49<1:29:58,  2.65s/it]

[PubChem fail] insulin, globin zinc: list index out of range

  7%|█████▌                                                                       | 157/2176 [06:29<1:27:56,  2.61s/it]

[PubChem fail] rituximab: list index out of range

  8%|█████▊                                                                       | 164/2176 [06:46<1:24:46,  2.53s/it]

[PubChem fail] atezolizumab: list index out of range

  8%|██████▍                                                                      | 181/2176 [07:28<1:24:15,  2.53s/it]

[PubChem fail] hyaluronic acid: list index out of range

  8%|██████▍                                                                      | 182/2176 [07:30<1:16:46,  2.31s/it]

[PubChem fail] abagovomab: list index out of range

  9%|██████▋                                                                      | 189/2176 [07:47<1:21:49,  2.47s/it]

[PubChem fail] blinatumomab: list index out of range

  9%|██████▉                                                                      | 195/2176 [08:01<1:21:02,  2.45s/it]

[PubChem fail] aldesleukin: list index out of range

  9%|███████                                                                      | 200/2176 [08:13<1:21:26,  2.47s/it]

Saved batch at 200 drugs
[PubChem fail] pertuzumab: list index out of range

  9%|███████▏                                                                     | 202/2176 [08:17<1:18:45,  2.39s/it]

[PubChem fail] quetmolimab: list index out of range

  9%|███████▎                                                                     | 206/2176 [08:27<1:19:32,  2.42s/it]

[PubChem fail] insulin aspart: list index out of range

 10%|███████▋                                                                     | 219/2176 [08:59<1:22:20,  2.52s/it]

[PubChem fail] durvalumab: list index out of range

 11%|████████▌                                                                    | 241/2176 [09:54<1:20:47,  2.51s/it]

[PubChem fail] vedolizumab: list index out of range

 11%|████████▋                                                                    | 246/2176 [10:05<1:17:14,  2.40s/it]

[PubChem fail] brodalumab: list index out of range

 12%|████████▉                                                                    | 253/2176 [10:22<1:21:05,  2.53s/it]

[PubChem fail] daratumumab: list index out of range

 12%|█████████▍                                                                   | 266/2176 [10:55<1:20:44,  2.54s/it]

[PubChem fail] patritumab deruxtecan: list index out of range

 13%|█████████▊                                                                   | 276/2176 [11:20<1:21:57,  2.59s/it]

[PubChem fail] panitumumab: list index out of range

 13%|██████████                                                                   | 286/2176 [11:45<1:22:16,  2.61s/it]

[PubChem fail] cemiplimab: list index out of range

 14%|██████████▌                                                                  | 300/2176 [12:20<1:20:57,  2.59s/it]

Saved batch at 300 drugs

 15%|███████████▊                                                                 | 335/2176 [13:51<1:24:10,  2.74s/it]

[PubChem fail] ramucirumab: list index out of range

 16%|████████████                                                                 | 342/2176 [14:08<1:17:11,  2.53s/it]

[PubChem fail] farletuzumab: list index out of range

 17%|████████████▊                                                                | 363/2176 [15:00<1:17:54,  2.58s/it]

[PubChem fail] avelumab: list index out of range

 17%|████████████▉                                                                | 365/2176 [15:05<1:12:39,  2.41s/it]

[PubChem fail] omalizumab: list index out of range

 17%|█████████████▏                                                               | 374/2176 [15:28<1:18:32,  2.62s/it]

[PubChem fail] alemtuzumab: list index out of range

 18%|█████████████▍                                                               | 381/2176 [15:45<1:14:20,  2.49s/it]

[PubChem fail] anetumab ravtansine: list index out of range

 18%|█████████████▋                                                               | 386/2176 [15:57<1:16:32,  2.57s/it]

[PubChem fail] cetuximab: list index out of range

 18%|█████████████▊                                                               | 390/2176 [16:07<1:14:04,  2.49s/it]

[PubChem fail] tisagenlecleucel: list index out of range

 18%|██████████████                                                               | 399/2176 [16:30<1:17:39,  2.62s/it]

[PubChem fail] ofatumumab: list index out of range

 18%|██████████████▏                                                              | 400/2176 [16:31<1:09:32,  2.35s/it]

Saved batch at 400 drugs

 19%|██████████████▎                                                              | 405/2176 [16:44<1:16:52,  2.60s/it]

[PubChem fail] spartalizumab: list index out of range

 19%|██████████████▌                                                              | 410/2176 [16:58<1:20:02,  2.72s/it]

[PubChem fail] sifalimumab: list index out of range

 19%|██████████████▋                                                              | 415/2176 [17:10<1:13:53,  2.52s/it]

[PubChem fail] butylated hydroxytoluene: list index out of range

 19%|██████████████▊                                                              | 417/2176 [17:15<1:09:25,  2.37s/it]

[PubChem fail] polyestradiol phosphate: list index out of range

 19%|██████████████▉                                                              | 421/2176 [17:24<1:09:24,  2.37s/it]

[PubChem fail] abobotulinumtoxina: list index out of range

 20%|███████████████▏                                                             | 429/2176 [17:43<1:13:40,  2.53s/it]

[PubChem fail] thrombin: list index out of range

 20%|███████████████▏                                                             | 430/2176 [17:45<1:06:55,  2.30s/it]

[PubChem fail] nimotuzumab: list index out of range

 20%|███████████████▎                                                             | 434/2176 [17:55<1:10:09,  2.42s/it]

[PubChem fail] daclizumab: list index out of range

 20%|███████████████▍                                                             | 436/2176 [17:59<1:09:02,  2.38s/it]

[PubChem fail] asparaginase: list index out of range

 20%|███████████████▋                                                             | 442/2176 [18:14<1:12:35,  2.51s/it]

[PubChem fail] pegaspargase: list index out of range

 21%|████████████████▏                                                            | 458/2176 [18:58<1:15:09,  2.62s/it]

[PubChem fail] carboxymethylcellulose sodium: list index out of range

 21%|████████████████▍                                                            | 465/2176 [19:18<1:24:32,  2.96s/it]

[PubChem fail] molgramostim: list index out of range

 22%|████████████████▊                                                            | 475/2176 [19:42<1:12:49,  2.57s/it]

[PubChem fail] plasminogen: list index out of range

 22%|████████████████▊                                                            | 476/2176 [19:44<1:05:43,  2.32s/it]

[PubChem fail] obinutuzumab: list index out of range

 22%|█████████████████▎                                                           | 489/2176 [20:17<1:10:40,  2.51s/it]

[PubChem fail] iron isomaltoside 1000: list index out of range

 23%|█████████████████▎                                                           | 490/2176 [20:19<1:03:48,  2.27s/it]

[PubChem fail] golimumab: list index out of range

 23%|█████████████████▍                                                           | 492/2176 [20:23<1:02:55,  2.24s/it]

[PubChem fail] mirikizumab: list index out of range

 23%|█████████████████▋                                                           | 500/2176 [20:43<1:12:34,  2.60s/it]

Saved batch at 500 drugs
[PubChem fail] lenograstim: list index out of range

 23%|█████████████████▉                                                           | 506/2176 [20:58<1:09:27,  2.50s/it]

[PubChem fail] lexatumumab: list index out of range

 25%|███████████████████▍                                                         | 551/2176 [22:55<1:11:16,  2.63s/it]

[PubChem fail] fezakinumab: list index out of range

 26%|███████████████████▋                                                         | 556/2176 [23:07<1:12:02,  2.67s/it]

[PubChem fail] adalimumab: list index out of range

 26%|███████████████████▊                                                         | 559/2176 [23:14<1:07:48,  2.52s/it]

[PubChem fail] ancrod: list index out of range

 26%|███████████████████▊                                                         | 561/2176 [23:19<1:06:58,  2.49s/it]

[PubChem fail] visilizumab: list index out of range

 26%|████████████████████                                                         | 567/2176 [23:35<1:15:46,  2.83s/it]

[PubChem fail] brentuximab vedotin: list index out of range

 26%|████████████████████▎                                                        | 574/2176 [23:53<1:10:19,  2.63s/it]

[PubChem fail] radium ra 223 dichloride: list index out of range

 27%|████████████████████▊                                                        | 588/2176 [24:27<1:07:05,  2.54s/it]

[PubChem fail] belimumab: list index out of range

 27%|█████████████████████                                                        | 595/2176 [24:44<1:05:43,  2.49s/it]

[PubChem fail] interferon beta-1a: list index out of range

 28%|█████████████████████▏                                                       | 600/2176 [24:57<1:07:09,  2.56s/it]

Saved batch at 600 drugs
[PubChem fail] tirzepatide: list index out of range

 29%|██████████████████████                                                       | 623/2176 [25:57<1:11:18,  2.75s/it]

[PubChem fail] erenumab: list index out of range

 29%|██████████████████████▎                                                      | 630/2176 [26:15<1:05:51,  2.56s/it]

[PubChem fail] abatacept: list index out of range

 29%|██████████████████████▉                                                        | 631/2176 [26:16<59:31,  2.31s/it]

[PubChem fail] bms-936559: list index out of range

 29%|██████████████████████▋                                                      | 641/2176 [26:42<1:06:58,  2.62s/it]

[PubChem fail] relatlimab: list index out of range

 30%|██████████████████████▉                                                      | 647/2176 [26:57<1:05:57,  2.59s/it]

[PubChem fail] peginterferon alfa-2a: list index out of range

 30%|███████████████████████▎                                                     | 659/2176 [27:27<1:07:40,  2.68s/it]

[PubChem fail] ustekinumab: list index out of range

 30%|███████████████████████▍                                                     | 661/2176 [27:32<1:01:45,  2.45s/it]

[PubChem fail] pancreatin: list index out of range

 30%|████████████████████████                                                       | 662/2176 [27:33<56:30,  2.24s/it]

[PubChem fail] pancrelipase: list index out of range

 31%|███████████████████████▋                                                     | 669/2176 [27:51<1:05:34,  2.61s/it]

[PubChem fail] peginterferon alfa-2b: list index out of range

 31%|███████████████████████▊                                                     | 674/2176 [28:04<1:04:31,  2.58s/it]

[PubChem fail] etanercept: list index out of range

 32%|████████████████████████▎                                                    | 686/2176 [28:34<1:03:08,  2.54s/it]

[PubChem fail] ixekizumab: list index out of range

 32%|████████████████████████▊                                                    | 700/2176 [29:09<1:02:40,  2.55s/it]

Saved batch at 700 drugs

 33%|█████████████████████████▍                                                   | 719/2176 [30:00<1:02:04,  2.56s/it]

[PubChem fail] trastuzumab deruxtecan: list index out of range

 34%|█████████████████████████▉                                                   | 733/2176 [30:36<1:01:00,  2.54s/it]

[PubChem fail] necitumumab: list index out of range

 34%|███████████████████████████                                                    | 745/2176 [31:06<59:14,  2.48s/it]

[PubChem fail] denosumab: list index out of range

 34%|███████████████████████████▏                                                   | 748/2176 [31:13<56:47,  2.39s/it]

[PubChem fail] denileukin diftitox: list index out of range

 35%|███████████████████████████▎                                                   | 754/2176 [31:27<59:53,  2.53s/it]

[PubChem fail] talimogene laherparepvec: list index out of range

 35%|███████████████████████████▌                                                   | 759/2176 [31:40<59:02,  2.50s/it]

[PubChem fail] infliximab: list index out of range

 35%|███████████████████████████▋                                                   | 761/2176 [31:44<55:47,  2.37s/it]

[PubChem fail] magrolimab: list index out of range

 36%|████████████████████████████▋                                                  | 791/2176 [33:00<59:45,  2.59s/it]

[PubChem fail] fasinumab: list index out of range

 37%|████████████████████████████▉                                                  | 797/2176 [33:14<56:40,  2.47s/it]

[PubChem fail] rasburicase: list index out of range

 37%|█████████████████████████████                                                  | 800/2176 [33:21<56:27,  2.46s/it]

Saved batch at 800 drugs

 37%|█████████████████████████████▎                                                 | 806/2176 [33:37<58:05,  2.54s/it]

[PubChem fail] lmb-100: list index out of range

 37%|█████████████████████████████▍                                                 | 810/2176 [33:46<56:40,  2.49s/it]

[PubChem fail] dacetuzumab: list index out of range

 39%|██████████████████████████████▋                                                | 844/2176 [35:15<56:44,  2.56s/it]

[PubChem fail] secretin: list index out of range

 39%|██████████████████████████████▉                                                | 853/2176 [35:37<56:54,  2.58s/it]

[PubChem fail] etrolizumab: list index out of range

 40%|███████████████████████████████▋                                               | 872/2176 [36:27<55:05,  2.54s/it]

[PubChem fail] lintuzumab: list index out of range

 40%|███████████████████████████████▊                                               | 875/2176 [36:34<51:42,  2.38s/it]

[PubChem fail] atoltivimab: list index out of range

 40%|███████████████████████████████▉                                               | 879/2176 [36:43<53:33,  2.48s/it]

[PubChem fail] mecasermin: list index out of range

 41%|████████████████████████████████▏                                              | 885/2176 [36:59<56:08,  2.61s/it]

[PubChem fail] rilotumumab: list index out of range

 41%|████████████████████████████████▍                                              | 895/2176 [37:25<55:50,  2.62s/it]

[PubChem fail] dostarlimab: list index out of range

 41%|████████████████████████████████▋                                              | 899/2176 [37:34<53:09,  2.50s/it]

[PubChem fail] ds-8273a: list index out of range

 41%|████████████████████████████████▋                                              | 900/2176 [37:36<48:30,  2.28s/it]

Saved batch at 900 drugs

 42%|████████████████████████████████▉                                              | 906/2176 [37:52<57:25,  2.71s/it]

[PubChem fail] alefacept: list index out of range

 42%|█████████████████████████████████▏                                             | 915/2176 [38:15<53:17,  2.54s/it]

[PubChem fail] labetuzumab: list index out of range

 43%|█████████████████████████████████▋                                             | 928/2176 [38:48<55:01,  2.65s/it]

[PubChem fail] zalutumumab: list index out of range

 43%|██████████████████████████████████▏                                            | 941/2176 [39:20<52:54,  2.57s/it]

[PubChem fail] polatuzumab vedotin: list index out of range

 44%|██████████████████████████████████▌                                            | 953/2176 [39:51<52:26,  2.57s/it]

[PubChem fail] polygeline: list index out of range

 44%|██████████████████████████████████▊                                            | 960/2176 [40:08<52:10,  2.57s/it]

[PubChem fail] olaratumab: list index out of range

 44%|██████████████████████████████████▉                                            | 962/2176 [40:13<48:56,  2.42s/it]

[PubChem fail] alirocumab: list index out of range

 44%|██████████████████████████████████▉                                            | 964/2176 [40:17<48:03,  2.38s/it]

[PubChem fail] tanezumab: list index out of range

 44%|███████████████████████████████████                                            | 965/2176 [40:19<44:19,  2.20s/it]

[PubChem fail] gemtuzumab: list index out of range

 45%|███████████████████████████████████▋                                           | 982/2176 [41:03<51:35,  2.59s/it]

[PubChem fail] incobotulinumtoxina: list index out of range

 46%|████████████████████████████████████▏                                          | 997/2176 [41:41<52:18,  2.66s/it]

[PubChem fail] loncastuximab tesirine: list index out of range

 46%|███████████████████████████████████▊                                          | 1000/2176 [41:48<48:37,  2.48s/it]

Saved batch at 1000 drugs

 46%|███████████████████████████████████▉                                          | 1002/2176 [41:53<49:20,  2.52s/it]

[PubChem fail] leronlimab: list index out of range

 47%|████████████████████████████████████▊                                         | 1028/2176 [43:00<51:00,  2.67s/it]

[PubChem fail] natalizumab: list index out of range

 47%|████████████████████████████████████▉                                         | 1030/2176 [43:04<47:39,  2.50s/it]

[PubChem fail] bococizumab: list index out of range

 47%|████████████████████████████████████▉                                         | 1032/2176 [43:09<44:47,  2.35s/it]

[PubChem fail] eculizumab: list index out of range

 48%|█████████████████████████████████████▊                                        | 1055/2176 [44:08<48:06,  2.58s/it]

[PubChem fail] petrolatum: list index out of range

 49%|██████████████████████████████████████                                        | 1061/2176 [44:23<47:08,  2.54s/it]

[PubChem fail] mogamulizumab: list index out of range

 49%|██████████████████████████████████████▏                                       | 1066/2176 [44:35<46:02,  2.49s/it]

[PubChem fail] poractant alfa: list index out of range

 49%|██████████████████████████████████████▌                                       | 1076/2176 [45:00<46:44,  2.55s/it]

[PubChem fail] siltuximab: list index out of range

 50%|██████████████████████████████████████▋                                       | 1081/2176 [45:12<45:25,  2.49s/it]

[PubChem fail] tislelizumab: list index out of range

 50%|██████████████████████████████████████▊                                       | 1082/2176 [45:13<40:52,  2.24s/it]

[PubChem fail] ranpirnase: list index out of range

 50%|███████████████████████████████████████                                       | 1091/2176 [45:36<46:12,  2.56s/it]

[PubChem fail] pidilizumab: list index out of range

 50%|███████████████████████████████████████▏                                      | 1094/2176 [45:42<42:42,  2.37s/it]

[PubChem fail] rilonacept: list index out of range

 51%|███████████████████████████████████████▍                                      | 1100/2176 [45:57<44:52,  2.50s/it]

Saved batch at 1100 drugs

 51%|███████████████████████████████████████▍                                      | 1101/2176 [46:00<46:02,  2.57s/it]

[PubChem fail] elotuzumab: list index out of range

 51%|████████████████████████████████████████                                      | 1118/2176 [46:44<47:13,  2.68s/it]

[PubChem fail] trebananib: list index out of range

 52%|████████████████████████████████████████▊                                     | 1137/2176 [47:33<44:39,  2.58s/it]

[PubChem fail] volagidemab: list index out of range

 52%|████████████████████████████████████████▉                                     | 1141/2176 [47:43<44:50,  2.60s/it]

[PubChem fail] tisotumab vedotin: list index out of range

 53%|████████████████████████████████████████▉                                     | 1143/2176 [47:47<41:07,  2.39s/it]

[PubChem fail] inotuzumab ozogamicin: list index out of range

 53%|█████████████████████████████████████████                                     | 1144/2176 [47:49<37:23,  2.17s/it]

[PubChem fail] muromonab-cd3: list index out of range

 53%|█████████████████████████████████████████                                     | 1146/2176 [47:53<37:26,  2.18s/it]

[PubChem fail] rindopepimut: list index out of range

 53%|█████████████████████████████████████████▏                                    | 1149/2176 [48:00<40:24,  2.36s/it]

[PubChem fail] ocrelizumab: list index out of range

 53%|█████████████████████████████████████████▎                                    | 1152/2176 [48:07<40:15,  2.36s/it]

[PubChem fail] ichthammol: list index out of range

 53%|█████████████████████████████████████████▋                                    | 1163/2176 [48:34<42:25,  2.51s/it]

[PubChem fail] veltuzumab: list index out of range

 54%|██████████████████████████████████████████▎                                   | 1180/2176 [49:18<42:49,  2.58s/it]

[PubChem fail] darbepoetin alfa: list index out of range

 54%|██████████████████████████████████████████▍                                   | 1183/2176 [49:25<42:53,  2.59s/it]

[PubChem fail] basiliximab: list index out of range

 55%|█████████████████████████████████████████▊                                  | 1196/2176 [50:12<1:07:14,  4.12s/it]

[PubChem fail] lumasiran: list index out of range

 55%|██████████████████████████████████████████▉                                   | 1198/2176 [50:17<55:49,  3.42s/it]

[PubChem fail] polyethylene glycol 3350: list index out of range

 55%|███████████████████████████████████████████                                   | 1200/2176 [50:22<48:23,  2.97s/it]

Saved batch at 1200 drugs

 55%|█████████████████████████████████████████▉                                  | 1202/2176 [50:32<1:00:36,  3.73s/it]

[PubChem fail] polymyxin b: list index out of range

 55%|███████████████████████████████████████████▏                                  | 1205/2176 [50:42<57:53,  3.58s/it]

[PubChem fail] conatumumab: list index out of range

 56%|███████████████████████████████████████████▎                                  | 1209/2176 [50:58<59:56,  3.72s/it]

[PubChem fail] naptumomab estafenatox: list index out of range

 56%|███████████████████████████████████████████▋                                  | 1220/2176 [51:33<45:42,  2.87s/it]

[PubChem fail] ravulizumab: list index out of range

 57%|████████████████████████████████████████████                                  | 1230/2176 [52:05<49:51,  3.16s/it]

[PubChem fail] cadexomer iodine: list index out of range

 57%|████████████████████████████████████████████▋                                 | 1248/2176 [53:13<48:06,  3.11s/it]

[PubChem fail] ibalizumab: list index out of range

 57%|████████████████████████████████████████████▊                                 | 1251/2176 [53:21<46:01,  2.99s/it]

[PubChem fail] ansuvimab: list index out of range

 58%|████████████████████████████████████████████                                | 1263/2176 [54:01<1:03:56,  4.20s/it]

[PubChem fail] dinutuximab: list index out of range

 59%|██████████████████████████████████████████████                                | 1284/2176 [55:42<42:35,  2.86s/it]

[PubChem fail] ethiodized oil: list index out of range

 59%|██████████████████████████████████████████████                                | 1285/2176 [55:44<37:30,  2.53s/it]

[PubChem fail] avdoralimab: list index out of range

 59%|██████████████████████████████████████████████▎                               | 1292/2176 [56:01<38:27,  2.61s/it]

[PubChem fail] mapatumumab: list index out of range

 60%|██████████████████████████████████████████████▌                               | 1300/2176 [56:21<37:17,  2.55s/it]

Saved batch at 1300 drugs

 61%|███████████████████████████████████████████████▊                              | 1333/2176 [57:47<36:45,  2.62s/it]

[PubChem fail] benralizumab: list index out of range

 62%|████████████████████████████████████████████████▏                             | 1344/2176 [58:14<35:10,  2.54s/it]

[PubChem fail] oregovomab: list index out of range

 62%|████████████████████████████████████████████████▏                             | 1346/2176 [58:19<34:38,  2.50s/it]

[PubChem fail] mineral oil: list index out of range

 62%|████████████████████████████████████████████████▎                             | 1347/2176 [58:21<31:36,  2.29s/it]

[PubChem fail] annexin a5: list index out of range

 62%|████████████████████████████████████████████████▍                             | 1351/2176 [58:32<36:03,  2.62s/it]

[PubChem fail] axicabtagene ciloleucel: list index out of range

 62%|████████████████████████████████████████████████▍                             | 1352/2176 [58:33<32:43,  2.38s/it]

[PubChem fail] lenzilumab: list index out of range

 62%|████████████████████████████████████████████████▌                             | 1355/2176 [58:40<32:51,  2.40s/it]

[PubChem fail] mavrilimumab: list index out of range

 63%|█████████████████████████████████████████████████                             | 1370/2176 [59:19<37:13,  2.77s/it]

[PubChem fail] pancreatic polypeptide: list index out of range

 63%|█████████████████████████████████████████████████▎                            | 1374/2176 [59:29<34:28,  2.58s/it]

[PubChem fail] oprelvekin: list index out of range

 63%|█████████████████████████████████████████████████▍                            | 1379/2176 [59:41<33:13,  2.50s/it]

[PubChem fail] bemarituzumab: list index out of range

 64%|█████████████████████████████████████████████████▌                            | 1383/2176 [59:50<32:16,  2.44s/it]

[PubChem fail] brexucabtagene autoleucel: list index out of range

 64%|████████████████████████████████████████████████▊                           | 1396/2176 [1:00:23<33:12,  2.55s/it]

[PubChem fail] verteporfin: list index out of range

 64%|████████████████████████████████████████████████▊                           | 1398/2176 [1:00:28<31:35,  2.44s/it]

[PubChem fail] gimsilumab: list index out of range

 64%|████████████████████████████████████████████████▉                           | 1400/2176 [1:00:32<29:21,  2.27s/it]

Saved batch at 1400 drugs

 65%|█████████████████████████████████████████████████▌                          | 1418/2176 [1:01:18<32:16,  2.55s/it]

[PubChem fail] certolizumab pegol: list index out of range

 66%|█████████████████████████████████████████████████▉                          | 1431/2176 [1:01:52<32:23,  2.61s/it]

[PubChem fail] cofetuzumab pelidotin: list index out of range

 66%|██████████████████████████████████████████████████▎                         | 1439/2176 [1:02:11<32:05,  2.61s/it]

[PubChem fail] plonmarlimab: list index out of range

 66%|██████████████████████████████████████████████████▌                         | 1447/2176 [1:02:31<29:48,  2.45s/it]

[PubChem fail] galiximab: list index out of range

 67%|██████████████████████████████████████████████████▉                         | 1458/2176 [1:02:59<30:53,  2.58s/it]

[PubChem fail] volociximab: list index out of range

 67%|██████████████████████████████████████████████████▉                         | 1460/2176 [1:03:03<29:08,  2.44s/it]

[PubChem fail] pf-06263507: list index out of range

 67%|███████████████████████████████████████████████████                         | 1462/2176 [1:03:08<27:28,  2.31s/it]

[PubChem fail] rimabotulinumtoxinb: list index out of range

 67%|███████████████████████████████████████████████████▏                        | 1467/2176 [1:03:20<29:18,  2.48s/it]

[PubChem fail] bamlanivimab: list index out of range

 68%|███████████████████████████████████████████████████▍                        | 1473/2176 [1:03:34<29:17,  2.50s/it]

[PubChem fail] evolocumab: list index out of range

 69%|████████████████████████████████████████████████████▎                       | 1497/2176 [1:04:35<28:10,  2.49s/it]

[PubChem fail] sotrovimab: list index out of range

 69%|████████████████████████████████████████████████████▍                       | 1500/2176 [1:04:42<28:24,  2.52s/it]

Saved batch at 1500 drugs
[PubChem fail] glembatumumab vedotin: list index out of range

 70%|█████████████████████████████████████████████████████                       | 1521/2176 [1:05:34<28:28,  2.61s/it]

[PubChem fail] gancotamab: list index out of range

 71%|█████████████████████████████████████████████████████▌                      | 1535/2176 [1:06:10<27:46,  2.60s/it]

[PubChem fail] bacitracin: list index out of range

 73%|███████████████████████████████████████████████████████▌                    | 1591/2176 [1:08:33<27:15,  2.80s/it]

[PubChem fail] tenecteplase: list index out of range

 73%|███████████████████████████████████████████████████████▊                    | 1599/2176 [1:08:53<24:39,  2.56s/it]

[PubChem fail] anti-inhibitor coagulant complex: list index out of range

 74%|███████████████████████████████████████████████████████▉                    | 1600/2176 [1:08:55<22:52,  2.38s/it]

Saved batch at 1600 drugs

 74%|████████████████████████████████████████████████████████▏                   | 1610/2176 [1:09:22<25:14,  2.68s/it]

[PubChem fail] pinatuzumab vedotin: list index out of range

 74%|████████████████████████████████████████████████████████▌                   | 1618/2176 [1:09:42<23:37,  2.54s/it]

[PubChem fail] zansecimab: list index out of range

 74%|████████████████████████████████████████████████████████▌                   | 1620/2176 [1:09:46<22:25,  2.42s/it]

[PubChem fail] colesevelam hydrochloride: list index out of range

 74%|████████████████████████████████████████████████████████▌                   | 1621/2176 [1:09:48<20:41,  2.24s/it]

[PubChem fail] rozanolixizumab: list index out of range

 75%|████████████████████████████████████████████████████████▋                   | 1622/2176 [1:09:50<19:22,  2.10s/it]

[PubChem fail] tilavonemab: list index out of range

 75%|████████████████████████████████████████████████████████▉                   | 1631/2176 [1:10:12<22:48,  2.51s/it]

[PubChem fail] glenzocimab: list index out of range

 75%|█████████████████████████████████████████████████████████                   | 1634/2176 [1:10:18<21:14,  2.35s/it]

[PubChem fail] becaplermin: list index out of range

 76%|█████████████████████████████████████████████████████████▊                  | 1655/2176 [1:11:11<21:56,  2.53s/it]

[PubChem fail] peppermint oil: list index out of range

 76%|█████████████████████████████████████████████████████████▊                  | 1657/2176 [1:11:16<20:31,  2.37s/it]

[PubChem fail] efungumab: list index out of range

 76%|██████████████████████████████████████████████████████████                  | 1664/2176 [1:11:32<21:14,  2.49s/it]

[PubChem fail] gelatin sponge, absorbable: list index out of range

 78%|███████████████████████████████████████████████████████████                 | 1691/2176 [1:12:41<21:19,  2.64s/it]

[PubChem fail] catumaxomab: list index out of range

 78%|███████████████████████████████████████████████████████████▏                | 1694/2176 [1:12:49<20:51,  2.60s/it]

[PubChem fail] interferon beta-1b: list index out of range

 78%|███████████████████████████████████████████████████████████▍                | 1700/2176 [1:13:06<22:00,  2.77s/it]

Saved batch at 1700 drugs

 78%|███████████████████████████████████████████████████████████▍                | 1701/2176 [1:13:08<21:53,  2.77s/it]

[PubChem fail] intetumumab: list index out of range

 78%|███████████████████████████████████████████████████████████▋                | 1708/2176 [1:13:26<19:39,  2.52s/it]

[PubChem fail] palivizumab: list index out of range

 79%|███████████████████████████████████████████████████████████▉                | 1717/2176 [1:13:48<20:17,  2.65s/it]

[PubChem fail] felzartamab: list index out of range

 81%|█████████████████████████████████████████████████████████████▌              | 1762/2176 [1:15:45<18:19,  2.66s/it]

[PubChem fail] indatuximab ravtansine: list index out of range

 81%|█████████████████████████████████████████████████████████████▌              | 1764/2176 [1:15:50<17:05,  2.49s/it]

[PubChem fail] luspatercept: list index out of range

 81%|█████████████████████████████████████████████████████████████▉              | 1772/2176 [1:16:09<17:20,  2.57s/it]

[PubChem fail] idecabtagene vicleucel: list index out of range

 82%|██████████████████████████████████████████████████████████████▎             | 1784/2176 [1:16:39<16:40,  2.55s/it]

[PubChem fail] castor oil: list index out of range

 82%|██████████████████████████████████████████████████████████████▌             | 1791/2176 [1:16:57<16:11,  2.52s/it]

[PubChem fail] mk-2640: list index out of range

 83%|██████████████████████████████████████████████████████████████▋             | 1796/2176 [1:17:10<16:31,  2.61s/it]

[PubChem fail] reslizumab: list index out of range

 83%|██████████████████████████████████████████████████████████████▊             | 1800/2176 [1:17:19<15:31,  2.48s/it]

Saved batch at 1800 drugs
[PubChem fail] calfactant: list index out of range

 83%|███████████████████████████████████████████████████████████████▎            | 1814/2176 [1:17:55<16:10,  2.68s/it]

[PubChem fail] saruplase: list index out of range

 84%|███████████████████████████████████████████████████████████████▋            | 1824/2176 [1:18:20<15:07,  2.58s/it]

[PubChem fail] remestemcel-l: list index out of range

 85%|████████████████████████████████████████████████████████████████▏           | 1839/2176 [1:18:57<14:03,  2.50s/it]

[PubChem fail] zanolimumab: list index out of range

 85%|████████████████████████████████████████████████████████████████▊           | 1856/2176 [1:19:40<13:50,  2.59s/it]

[PubChem fail] vilobelimab: list index out of range

 86%|█████████████████████████████████████████████████████████████████           | 1863/2176 [1:19:57<13:19,  2.55s/it]

[PubChem fail] beractant: list index out of range

 86%|█████████████████████████████████████████████████████████████████▋          | 1880/2176 [1:20:40<12:30,  2.54s/it]

[PubChem fail] astegolimab: list index out of range

 87%|██████████████████████████████████████████████████████████████████▏         | 1895/2176 [1:21:18<11:49,  2.53s/it]

[PubChem fail] abciximab: list index out of range

 87%|██████████████████████████████████████████████████████████████████▎         | 1900/2176 [1:21:30<11:24,  2.48s/it]

Saved batch at 1900 drugs

 88%|██████████████████████████████████████████████████████████████████▋         | 1910/2176 [1:21:55<11:20,  2.56s/it]

[PubChem fail] faricimab: list index out of range

 88%|██████████████████████████████████████████████████████████████████▊         | 1912/2176 [1:22:00<10:33,  2.40s/it]

[PubChem fail] streptokinase: list index out of range

 89%|███████████████████████████████████████████████████████████████████▌        | 1935/2176 [1:22:58<10:37,  2.65s/it]

[PubChem fail] edrecolomab: list index out of range

 91%|████████████████████████████████████████████████████████████████████▉       | 1975/2176 [1:24:42<08:38,  2.58s/it]

[PubChem fail] ecromeximab: list index out of range

 91%|█████████████████████████████████████████████████████████████████████▏      | 1982/2176 [1:24:59<08:11,  2.53s/it]

[PubChem fail] disitamab vedotin: list index out of range

 92%|█████████████████████████████████████████████████████████████████████▊      | 2000/2176 [1:25:46<07:57,  2.71s/it]

Saved batch at 2000 drugs
[PubChem fail] reteplase: list index out of range

 94%|███████████████████████████████████████████████████████████████████████▎    | 2041/2176 [1:27:31<05:53,  2.62s/it]

[PubChem fail] opium: list index out of range

 94%|███████████████████████████████████████████████████████████████████████▍    | 2047/2176 [1:27:47<05:48,  2.71s/it]

[PubChem fail] interferon alfacon-1: list index out of range

 96%|█████████████████████████████████████████████████████████████████████████   | 2092/2176 [1:29:44<03:37,  2.59s/it]

[PubChem fail] abetimus: list index out of range

 97%|█████████████████████████████████████████████████████████████████████████▎  | 2100/2176 [1:30:03<03:10,  2.50s/it]

Saved batch at 2100 drugs

 97%|█████████████████████████████████████████████████████████████████████████▋  | 2110/2176 [1:30:29<02:52,  2.61s/it]

[PubChem fail] efpeglenatide: list index out of range

 97%|█████████████████████████████████████████████████████████████████████████▊  | 2113/2176 [1:30:36<02:34,  2.46s/it]

[PubChem fail] actovegin: list index out of range

100%|████████████████████████████████████████████████████████████████████████████| 2176/2176 [1:33:18<00:00,  2.57s/it]

Enrichment complete. Saved to final_drug_info.csv

In [7]:
drug_info_df

,drug_name,smiles,iupac,molecular_weight,synonyms,max_phase,drug_type,mechanism,target,description
0,succimer,C(C(C(=O)O)S)(C(=O)O)S,"(2S,3R)-2,3-bis(sulfanyl)butanedioic acid",182.2,Succimer; Dim-sa; meso-Dimercaptosuccinic acid...,4.0,Small molecule,Lead chelating agent,None,NaN
1,sargramostim,None,None,None,None,4.0,Protein,Granulocyte-macrophage colony-stimulating fact...,None,NaN
2,caffeine,CN1C=NC2=C1C(=O)N(C(=O)N2C)C,"1,3,7-trimethylpurine-2,6-dione",194.19,"caffeine; 58-08-2; Guaranine; 1,3,7-Trimethylx...",4.0,Small molecule,Adenosine receptor antagonist,None,NaN
3,apixaban,COC1=CC=C(C=C1)N2C3=C(CCN(C3=O)C4=CC=C(C=C4)N5...,1-(4-methoxyphenyl)-7-oxo-6-[4-(2-oxopiperidin...,459.5,Apixaban; 503612-47-3; BMS-562247-01; BMS 5622...,4.0,Small molecule,Coagulation factor X inhibitor,None,NaN
4,ibrexafungerp,CC(C)C(C)C1(CCC2(C3CCC4C5(COCC4(C3=CCC2(C1C(=O...,"(1R,5S,6R,7R,10R,11R,14R,15S,20R,21R)-21-[(2R)...",730.0,Ibrexafungerp; SCY-078; 1207753-03-4; MK-3118;...,4.0,Small molecule,"1,3-beta-glucan synthase inhibitor",None,NaN
...,...,...,...,...,...,...,...,...,...,...
2171,porfiromycin,CC1=C(C(=O)C2=C(C1=O)N3CC4C(C3(C2COC(=O)N)OC)N...,"[(4S,6S,7R,8S)-11-amino-7-methoxy-5,12-dimethy...",348.35,Porfiromycin; 801-52-5; N-Methylmitomycin C; M...,3.0,Small molecule,None,None,NaN
2172,penciclovir,C1=NC2=C(N1CCC(CO)CO)N=C(NC2=O)N,2-amino-9-[4-hydroxy-3-(hydroxymethyl)butyl]-1...,253.26,penciclovir; 39809-25-1; Denavir; Pencicloviru...,4.0,Small molecule,Human herpesvirus 1 DNA polymerase inhibitor,None,NaN
2173,cinitapride,CCOC1=CC(=C(C=C1C(=O)NC2CCN(CC2)CC3CCC=CC3)[N+...,4-amino-N-[1-(cyclohex-3-en-1-ylmethyl)piperid...,402.5,Cinitapride; 66564-14-5; Paxapride; Cinitaprid...,3.0,Small molecule,None,None,NaN
2174,melagatran,C1CCC(CC1)C(C(=O)N2CCC2C(=O)NCC3=CC=C(C=C3)C(=...,2-[[(1R)-2-[(2S)-2-[(4-carbamimidoylphenyl)met...,429.5,Melagatran; 159776-70-2; Melagatran [INN]; UNI...,4.0,Small molecule,None,None,NaN
2175,pranlukast,C1=CC=C(C=C1)CCCCOC2=CC=C(C=C2)C(=O)NC3=CC=CC4...,N-[4-oxo-2-(2H-tetrazol-5-yl)chromen-8-yl]-4-(...,481.5,Pranlukast; 103177-37-3; Azlaire; Ono-1078; ON...,4.0,Small molecule,Cysteinyl leukotriene receptor 1 antagonist,None,NaN

In [8]:
# 9. Merge back to trial data
df_merged = df_expanded.merge(drug_info_df, on='drug_name', how='left').drop_duplicates(subset=['nct_id', 'drug_name'])

def _is_number(val):
    try:
        float(val)
        return True
    except (ValueError, TypeError):
        return False
        
# 10. Collapse per trial
grouped = df_merged.groupby('nct_id').agg({
    'drug_name': lambda x: '; '.join(sorted(set(x.dropna()))),
    'smiles': lambda x: '; '.join(sorted(set(x.dropna()))),
    'description': lambda x: '; '.join(sorted(set(x.dropna()))),
    'iupac': lambda x: '; '.join(sorted(set(x.dropna()))),
    'molecular_weight': lambda x: '; '.join(
        str(round(float(v), 2)) for v in set(x.dropna()) if _is_number(v)
    ),
    'synonyms': lambda x: '; '.join(sorted(set(x.dropna()))),
    'max_phase': lambda x: '; '.join(str(p) for p in set(x.dropna())),
    'drug_type': lambda x: '; '.join(sorted(set(x.dropna()))),
    'mechanism': lambda x: '; '.join(sorted(set(x.dropna()))),
    'target': lambda x: '; '.join(sorted(set(x.dropna()))),
}).reset_index()

In [9]:
grouped

,nct_id,drug_name,smiles,description,iupac,molecular_weight,synonyms,max_phase,drug_type,mechanism,target
0,NCT00000114,vitamin e,CC1=C(C2=C(CCC(O2)(C)CCCC(C)CCCC(C)CCCC(C)C)C(...,,"(2R)-2,5,7,8-tetramethyl-2-[(4R,8R)-4,8,12-tri...",430.7,alpha-Tocopherol; alpha Tocopherol; Phytogermi...,4.0,Unknown,,
1,NCT00000115,acetazolamide,CC(=O)NC1=NN=C(S1)S(=O)(=O)N,,"N-(5-sulfamoyl-1,3,4-thiadiazol-2-yl)acetamide",222.3,acetazolamide; 59-66-5; Acetamox; Nephramide; ...,4.0,Small molecule,Carbonic anhydrase I inhibitor,
2,NCT00000122,fluorouracil,C1=C(C(=O)NC(=O)N1)F,,"5-fluoro-1H-pyrimidine-2,4-dione",130.08,5-Fluorouracil; fluorouracil; 5-FU; Fluracil; ...,4.0,Small molecule,Thymidylate synthase inhibitor,
3,NCT00000134,foscarnet; ganciclovir,C(=O)(O)P(=O)(O)O; C1=NC2=C(N1COC(CO)CO)N=C(NC...,,"2-amino-9-(1,3-dihydroxypropan-2-yloxymethyl)-...",255.23; 126.01,foscarnet; Phosphonoformic acid; Carboxyphosph...,4.0,Small molecule,Human herpesvirus 1 DNA polymerase inhibitor,
4,NCT00000136,foscarnet; ganciclovir,C(=O)(O)P(=O)(O)O; C1=NC2=C(N1COC(CO)CO)N=C(NC...,,"2-amino-9-(1,3-dihydroxypropan-2-yloxymethyl)-...",255.23; 126.01,foscarnet; Phosphonoformic acid; Carboxyphosph...,4.0,Small molecule,Human herpesvirus 1 DNA polymerase inhibitor,
...,...,...,...,...,...,...,...,...,...,...,...
61519,NCT06649409,eplerenone; fludrocortisone,CC12CCC(=O)C=C1CC(C3C24C(O4)CC5(C3CCC56CCC(=O)...,,"(8S,9R,10S,11S,13S,14S,17R)-9-fluoro-11,17-dih...",380.4; 414.5,Eplerenone; Selara; SC-66110; CGP-30083; Epler...,4.0; 2.0,Small molecule,Mineralocorticoid receptor antagonist,
61520,NCT06654531,dexmedetomidine,CC1=C(C(=CC=C1)C(C)C2=CN=CN2)C,,"5-[(1S)-1-(2,3-dimethylphenyl)ethyl]-1H-imidazole",200.28,DEXMEDETOMIDINE; 113775-47-6; Dexmedetomidina;...,4.0,Small molecule,,
61521,NCT06654570,letrozole,C1=CC(=CC=C1C#N)C(C2=CC=C(C=C2)C#N)N3C=NC=N3,,"4-[(4-cyanophenyl)-(1,2,4-triazol-1-yl)methyl]...",285.3,"letrozole; 112809-51-5; 4,4'-((1h-1,2,4-triazo...",4.0,Small molecule,Cytochrome P450 19A1 inhibitor,
61522,NCT06655818,dostarlimab,,,,,,4.0,Antibody,Programmed cell death protein 1 antagonist,
61523,NCT06657066,albuterol; beclomethasone; formoterol fumarate,CC(C)(C)NCC(C1=CC(=C(C=C1)O)CO)O; CC(CC1=CC=C(...,,"(8S,9R,10S,11S,13S,14S,16S,17R)-9-chloro-11,17...",840.9; 408.9; 239.31,Formoterol fumarate dihydrate; Perforomist; UN...,4.0; 2.0,Small molecule,Beta-2 adrenergic receptor agonist,

In [11]:
grouped

,nct_id,drug_name,smiles,description,iupac,molecular_weight,synonyms,max_phase,drug_type,mechanism,target
0,NCT00000114,vitamin e,CC1=C(C2=C(CCC(O2)(C)CCCC(C)CCCC(C)CCCC(C)C)C(...,,"(2R)-2,5,7,8-tetramethyl-2-[(4R,8R)-4,8,12-tri...",430.7,VITAMIN E; alpha-Tocopherol; 59-02-9; D-alpha-...,4.0,Unknown,,
1,NCT00000115,acetazolamide,CC(=O)NC1=NN=C(S1)S(=O)(=O)N,,"N-(5-sulfamoyl-1,3,4-thiadiazol-2-yl)acetamide",222.3,acetazolamide; 59-66-5; Diamox; Acetamox; Neph...,4.0,Small molecule,Carbonic anhydrase I inhibitor,
2,NCT00000122,fluorouracil,C1=C(C(=O)NC(=O)N1)F,,"5-fluoro-1H-pyrimidine-2,4-dione",130.08,5-Fluorouracil; fluorouracil; 51-21-8; 5-FU; F...,4.0,Small molecule,Thymidylate synthase inhibitor,
3,NCT00000134,foscarnet; ganciclovir,C(=O)(O)P(=O)(O)O; C1=NC2=C(N1COC(CO)CO)N=C(NC...,,"2-amino-9-(1,3-dihydroxypropan-2-yloxymethyl)-...",126.01; 255.23,foscarnet; Phosphonoformic acid; Phosphonoform...,4.0,Small molecule,Human herpesvirus 1 DNA polymerase inhibitor,
4,NCT00000136,foscarnet; ganciclovir,C(=O)(O)P(=O)(O)O; C1=NC2=C(N1COC(CO)CO)N=C(NC...,,"2-amino-9-(1,3-dihydroxypropan-2-yloxymethyl)-...",126.01; 255.23,foscarnet; Phosphonoformic acid; Phosphonoform...,4.0,Small molecule,Human herpesvirus 1 DNA polymerase inhibitor,
...,...,...,...,...,...,...,...,...,...,...,...
61519,NCT06649409,eplerenone; fludrocortisone,CC12CCC(=O)C=C1CC(C3C24C(O4)CC5(C3CCC56CCC(=O)...,,"(8S,9R,10S,11S,13S,14S,17R)-9-fluoro-11,17-dih...",414.5; 380.4,Eplerenone; Inspra; Epoxymexrenone; 107724-20-...,2.0; 4.0,Small molecule,Mineralocorticoid receptor antagonist,
61520,NCT06654531,dexmedetomidine,CC1=C(C(=CC=C1)C(C)C2=CN=CN2)C,,"5-[(1S)-1-(2,3-dimethylphenyl)ethyl]-1H-imidazole",200.28,DEXMEDETOMIDINE; 113775-47-6; Dexmedetomidina;...,4.0,Small molecule,,
61521,NCT06654570,letrozole,C1=CC(=CC=C1C#N)C(C2=CC=C(C=C2)C#N)N3C=NC=N3,,"4-[(4-cyanophenyl)-(1,2,4-triazol-1-yl)methyl]...",285.3,"letrozole; 112809-51-5; Femara; 4,4'-((1h-1,2,...",4.0,Small molecule,Cytochrome P450 19A1 inhibitor,
61522,NCT06655818,dostarlimab,,,,,,4.0,Antibody,Programmed cell death protein 1 antagonist,
61523,NCT06657066,albuterol; beclomethasone; formoterol fumarate,CC(C)(C)NCC(C1=CC(=C(C=C1)O)CO)O; CC(CC1=CC=C(...,,"(8S,9R,10S,11S,13S,14S,16S,17R)-9-chloro-11,17...",408.9; 804.9; 239.31,Formoterol hemifumarate; 43229-80-7; FORMOTERO...,2.0; 4.0,Small molecule,Beta-2 adrenergic receptor agonist,

In [16]:
trial_metadata = df.drop_duplicates(subset='nct_id')

# Merge metadata into your grouped dataset (1 row per nct_id)
grouped_enriched = grouped.merge(trial_metadata, on='nct_id', how='left')
grouped_enriched

,nct_id,drug_name,smiles,description,iupac,molecular_weight,synonyms,max_phase,drug_type,mechanism,...,healthy_volunteers,population,criteria,gender_description,gender_based,adult,child,older_adult,design,features
0,NCT00000114,vitamin e,CC1=C(C2=C(CCC(O2)(C)CCCC(C)CCCC(C)CCCC(C)C)C(...,,"(2R)-2,5,7,8-tetramethyl-2-[(4R,8R)-4,8,12-tri...",430.7,VITAMIN E; alpha-Tocopherol; 59-02-9; D-alpha-...,4.0,Unknown,,...,NaN,NaN,men and nonpregnant women between ages 18 and ...,NaN,NaN,t,f,f,randomized factorial treatment double,PHASE3 retinal diseases; eye diseases; eye dis...
1,NCT00000115,acetazolamide,CC(=O)NC1=NN=C(S1)S(=O)(=O)N,,"N-(5-sulfamoyl-1,3,4-thiadiazol-2-yl)acetamide",222.3,acetazolamide; 59-66-5; Diamox; Acetamox; Neph...,4.0,Small molecule,Carbonic anhydrase I inhibitor,...,NaN,NaN,males and females 8 years of age or older and ...,NaN,NaN,t,t,t,randomized crossover treatment double,PHASE2 macular degeneration; retinal degenerat...
2,NCT00000122,fluorouracil,C1=C(C(=O)NC(=O)N1)F,,"5-fluoro-1H-pyrimidine-2,4-dione",130.08,5-Fluorouracil; fluorouracil; 51-21-8; 5-FU; F...,4.0,Small molecule,Thymidylate synthase inhibitor,...,f,NaN,men and women with uncontrolled intraocular pr...,NaN,NaN,t,t,t,randomized treatment double,PHASE3 ocular hypertension; eye diseases; glau...
3,NCT00000134,foscarnet; ganciclovir,C(=O)(O)P(=O)(O)O; C1=NC2=C(N1COC(CO)CO)N=C(NC...,,"2-amino-9-(1,3-dihydroxypropan-2-yloxymethyl)-...",126.01; 255.23,foscarnet; Phosphonoformic acid; Phosphonoform...,4.0,Small molecule,Human herpesvirus 1 DNA polymerase inhibitor,...,f,NaN,inclusion criteria: males and females eligible...,NaN,NaN,t,f,t,randomized factorial treatment double,PHASE3 blood-borne infections; communicable di...
4,NCT00000136,foscarnet; ganciclovir,C(=O)(O)P(=O)(O)O; C1=NC2=C(N1COC(CO)CO)N=C(NC...,,"2-amino-9-(1,3-dihydroxypropan-2-yloxymethyl)-...",126.01; 255.23,foscarnet; Phosphonoformic acid; Phosphonoform...,4.0,Small molecule,Human herpesvirus 1 DNA polymerase inhibitor,...,f,NaN,inclusion criteria:~* cmv retinitis in one or ...,NaN,NaN,t,t,t,randomized parallel treatment single,PHASE3 infections; virus diseases; retinal dis...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61519,NCT06649409,eplerenone; fludrocortisone,CC12CCC(=O)C=C1CC(C3C24C(O4)CC5(C3CCC56CCC(=O)...,,"(8S,9R,10S,11S,13S,14S,17R)-9-fluoro-11,17-dih...",414.5; 380.4,Eplerenone; Inspra; Epoxymexrenone; 107724-20-...,2.0; 4.0,Small molecule,Mineralocorticoid receptor antagonist,...,t,NaN,inclusion criteria:~1. age of 18 to 55 years i...,NaN,NaN,t,f,f,randomized parallel other none,PHASE1 anti-inflammatory agents; antihyperten...
61520,NCT06654531,dexmedetomidine,CC1=C(C(=CC=C1)C(C)C2=CN=CN2)C,,"5-[(1S)-1-(2,3-dimethylphenyl)ethyl]-1H-imidazole",200.28,DEXMEDETOMIDINE; 113775-47-6; Dexmedetomidina;...,4.0,Small molecule,,...,f,NaN,inclusion criteria:~* asa physical status i-ii...,NaN,NaN,t,f,f,randomized parallel prevention none,PHASE2/PHASE3 adrenergic agents; adrenergic a...
61521,NCT06654570,letrozole,C1=CC(=CC=C1C#N)C(C2=CC=C(C=C2)C#N)N3C=NC=N3,,"4-[(4-cyanophenyl)-(1,2,4-triazol-1-yl)methyl]...",285.3,"letrozole; 112809-51-5; Femara; 4,4'-((1h-1,2,...",4.0,Small molecule,Cytochrome P450 19A1 inhibitor,...,f,NaN,inclusion criteria:~* eligible patients were p...,Females,t,t,f,t,single_group treatment none,PHASE2 neoplasms by site; neoplasms; breast di...
61522,NCT06655818,dostarlimab,,,,,,4.0,Antibody,Programmed cell death protein 1 antagonist,...,f,NaN,inclusion criteria:~* participant must be 18 y...,NaN,NaN,t,f,t,single_group treatment none,PHASE1/PHASE2 neoplasms by histologic type; ne...
61523,NCT06657066,albuterol; beclomethasone; formoterol fumarate,CC(C)(C)NCC(C1=CC(=C(C=C1)O)CO)O; CC(CC1=CC=C(...,,"(8S,9R,10S,11S,13S,14S,16S,17R)-9-chloro-11,17...",408.9; 804.9; 239.31,Formoterol hemifumarate; 43229-80-7; FORMOTERO...,2.0; 4.0,Small molecule,Beta-2 adrenergic receptor agonist,...,f,NaN,inclusion criteria~1. patient of both genders ...,NaN,NaN,t,f,t,randomized parallel treatment double,PHASE2/PHASE3 bronchial diseases; respiratory ...

In [17]:
cols = ['nct_id'] + [col for col in grouped_enriched.columns if col != 'nct_id']
grouped_enriched = grouped_enriched[cols]
grouped_enriched

,nct_id,drug_name,smiles,description,iupac,molecular_weight,synonyms,max_phase,drug_type,mechanism,...,healthy_volunteers,population,criteria,gender_description,gender_based,adult,child,older_adult,design,features
0,NCT00000114,vitamin e,CC1=C(C2=C(CCC(O2)(C)CCCC(C)CCCC(C)CCCC(C)C)C(...,,"(2R)-2,5,7,8-tetramethyl-2-[(4R,8R)-4,8,12-tri...",430.7,VITAMIN E; alpha-Tocopherol; 59-02-9; D-alpha-...,4.0,Unknown,,...,NaN,NaN,men and nonpregnant women between ages 18 and ...,NaN,NaN,t,f,f,randomized factorial treatment double,PHASE3 retinal diseases; eye diseases; eye dis...
1,NCT00000115,acetazolamide,CC(=O)NC1=NN=C(S1)S(=O)(=O)N,,"N-(5-sulfamoyl-1,3,4-thiadiazol-2-yl)acetamide",222.3,acetazolamide; 59-66-5; Diamox; Acetamox; Neph...,4.0,Small molecule,Carbonic anhydrase I inhibitor,...,NaN,NaN,males and females 8 years of age or older and ...,NaN,NaN,t,t,t,randomized crossover treatment double,PHASE2 macular degeneration; retinal degenerat...
2,NCT00000122,fluorouracil,C1=C(C(=O)NC(=O)N1)F,,"5-fluoro-1H-pyrimidine-2,4-dione",130.08,5-Fluorouracil; fluorouracil; 51-21-8; 5-FU; F...,4.0,Small molecule,Thymidylate synthase inhibitor,...,f,NaN,men and women with uncontrolled intraocular pr...,NaN,NaN,t,t,t,randomized treatment double,PHASE3 ocular hypertension; eye diseases; glau...
3,NCT00000134,foscarnet; ganciclovir,C(=O)(O)P(=O)(O)O; C1=NC2=C(N1COC(CO)CO)N=C(NC...,,"2-amino-9-(1,3-dihydroxypropan-2-yloxymethyl)-...",126.01; 255.23,foscarnet; Phosphonoformic acid; Phosphonoform...,4.0,Small molecule,Human herpesvirus 1 DNA polymerase inhibitor,...,f,NaN,inclusion criteria: males and females eligible...,NaN,NaN,t,f,t,randomized factorial treatment double,PHASE3 blood-borne infections; communicable di...
4,NCT00000136,foscarnet; ganciclovir,C(=O)(O)P(=O)(O)O; C1=NC2=C(N1COC(CO)CO)N=C(NC...,,"2-amino-9-(1,3-dihydroxypropan-2-yloxymethyl)-...",126.01; 255.23,foscarnet; Phosphonoformic acid; Phosphonoform...,4.0,Small molecule,Human herpesvirus 1 DNA polymerase inhibitor,...,f,NaN,inclusion criteria:~* cmv retinitis in one or ...,NaN,NaN,t,t,t,randomized parallel treatment single,PHASE3 infections; virus diseases; retinal dis...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61519,NCT06649409,eplerenone; fludrocortisone,CC12CCC(=O)C=C1CC(C3C24C(O4)CC5(C3CCC56CCC(=O)...,,"(8S,9R,10S,11S,13S,14S,17R)-9-fluoro-11,17-dih...",414.5; 380.4,Eplerenone; Inspra; Epoxymexrenone; 107724-20-...,2.0; 4.0,Small molecule,Mineralocorticoid receptor antagonist,...,t,NaN,inclusion criteria:~1. age of 18 to 55 years i...,NaN,NaN,t,f,f,randomized parallel other none,PHASE1 anti-inflammatory agents; antihyperten...
61520,NCT06654531,dexmedetomidine,CC1=C(C(=CC=C1)C(C)C2=CN=CN2)C,,"5-[(1S)-1-(2,3-dimethylphenyl)ethyl]-1H-imidazole",200.28,DEXMEDETOMIDINE; 113775-47-6; Dexmedetomidina;...,4.0,Small molecule,,...,f,NaN,inclusion criteria:~* asa physical status i-ii...,NaN,NaN,t,f,f,randomized parallel prevention none,PHASE2/PHASE3 adrenergic agents; adrenergic a...
61521,NCT06654570,letrozole,C1=CC(=CC=C1C#N)C(C2=CC=C(C=C2)C#N)N3C=NC=N3,,"4-[(4-cyanophenyl)-(1,2,4-triazol-1-yl)methyl]...",285.3,"letrozole; 112809-51-5; Femara; 4,4'-((1h-1,2,...",4.0,Small molecule,Cytochrome P450 19A1 inhibitor,...,f,NaN,inclusion criteria:~* eligible patients were p...,Females,t,t,f,t,single_group treatment none,PHASE2 neoplasms by site; neoplasms; breast di...
61522,NCT06655818,dostarlimab,,,,,,4.0,Antibody,Programmed cell death protein 1 antagonist,...,f,NaN,inclusion criteria:~* participant must be 18 y...,NaN,NaN,t,f,t,single_group treatment none,PHASE1/PHASE2 neoplasms by histologic type; ne...
61523,NCT06657066,albuterol; beclomethasone; formoterol fumarate,CC(C)(C)NCC(C1=CC(=C(C=C1)O)CO)O; CC(CC1=CC=C(...,,"(8S,9R,10S,11S,13S,14S,16S,17R)-9-chloro-11,17...",408.9; 804.9; 239.31,Formoterol hemifumarate; 43229-80-7; FORMOTERO...,2.0; 4.0,Small molecule,Beta-2 adrenergic receptor agonist,...,f,NaN,inclusion criteria~1. patient of both genders ...,NaN,NaN,t,f,t,randomized parallel treatment double,PHASE2/PHASE3 bronchial diseases; respiratory ...

In [18]:
grouped_enriched.to_csv("drugs2smiles.csv", index=False)
print("SAVED")

SAVED

In [35]:
drug_info_df.to_csv("druginfo.csv", index=False)

In [45]:
import pandas as pd

# Load both datasets
druginfo = pd.read_csv("druginfo.csv")
drugbank_info = pd.read_csv("Data/drugbank_drugs_info.csv")

C:\Users\Asus\AppData\Local\Temp\ipykernel_22612\2593809334.py:5: DtypeWarning: Columns (30) have mixed types. Specify dtype option on import or set low_memory=False.
  drugbank_info = pd.read_csv("Data/drugbank_drugs_info.csv")

In [48]:
druginfo['drug_name'] = druginfo['drug_name'].astype(str).str.lower().str.strip()
drugbank_info['title'] = drugbank_info['title'].astype(str).str.lower().str.strip()

In [49]:
# Merge using 'drug_name' from druginfo and 'title' from drugbank_info
merged = druginfo.merge(
    drugbank_info[['title', 'description']],
    left_on='drug_name',
    right_on='title',
    how='left'
)

merged = merged.drop(columns=['title'])

In [50]:
merged

,drug_name,smiles,iupac,molecular_weight,synonyms,description_x,max_phase,drug_type,mechanism,target,description_y
0,succimer,NaN,NaN,NaN,NaN,NaN,4.0,Small molecule,Lead chelating agent,NaN,"Succimer (2,3-meso-dimercaptosuccinic acid) is..."
1,succimer,NaN,NaN,NaN,NaN,NaN,4.0,Small molecule,Lead chelating agent,NaN,NaN
2,sargramostim,NaN,NaN,NaN,NaN,NaN,4.0,Protein,Granulocyte-macrophage colony-stimulating fact...,NaN,NaN
3,sargramostim,NaN,NaN,NaN,NaN,NaN,4.0,Protein,Granulocyte-macrophage colony-stimulating fact...,NaN,NaN
4,sargramostim,NaN,NaN,NaN,NaN,NaN,4.0,Protein,Granulocyte-macrophage colony-stimulating fact...,NaN,\N
...,...,...,...,...,...,...,...,...,...,...,...
90613,porfiromycin,CC1=C(C(=O)C2=C(C1=O)N3CC4C(C3(C2COC(=O)N)OC)N...,"[(4S,6S,7R,8S)-11-amino-7-methoxy-5,12-dimethy...",348.35,Porfiromycin; 801-52-5; N-Methylmitomycin C; M...,NaN,3.0,Small molecule,NaN,NaN,NaN
90614,penciclovir,C1=NC2=C(N1CCC(CO)CO)N=C(NC2=O)N,2-amino-9-[4-hydroxy-3-(hydroxymethyl)butyl]-1...,253.26,penciclovir; 39809-25-1; Denavir; Pencicloviru...,NaN,4.0,Small molecule,Human herpesvirus 1 DNA polymerase inhibitor,NaN,Penciclovir every 2 hours during waking hours ...
90615,cinitapride,CCOC1=CC(=C(C=C1C(=O)NC2CCN(CC2)CC3CCC=CC3)[N+...,4-amino-N-[1-(cyclohex-3-en-1-ylmethyl)piperid...,402.50,Cinitapride; 66564-14-5; Paxapride; Cinitaprid...,NaN,3.0,Small molecule,NaN,NaN,"cinitapride 1 mg for each dose, 3 mg/daily, fo..."
90616,melagatran,C1CCC(CC1)C(C(=O)N2CCC2C(=O)NCC3=CC=C(C=C3)C(=...,2-[[(1R)-2-[(2S)-2-[(4-carbamimidoylphenyl)met...,429.50,Melagatran; 159776-70-2; Melagatran [INN]; UNI...,NaN,4.0,Small molecule,NaN,NaN,NaN
90617,pranlukast,C1=CC=C(C=C1)CCCCOC2=CC=C(C=C2)C(=O)NC3=CC=CC4...,N-[4-oxo-2-(2H-tetrazol-5-yl)chromen-8-yl]-4-(...,481.50,Pranlukast; 103177-37-3; Azlaire; Ono-1078; ON...,NaN,4.0,Small molecule,Cysteinyl leukotriene receptor 1 antagonist,NaN,NaN

In [55]:
# 2. Data normalization
druginfo['drug_name'] = druginfo['drug_name'].astype(str).str.lower().str.strip()
drugbank_info['title'] = drugbank_info['title'].astype(str).str.lower().str.strip()

# 3. Remove duplicates 
drugbank_dedup = drugbank_info.drop_duplicates(subset='title')

# 4. Merge
merged = druginfo.merge(
    drugbank_dedup[['title', 'description']],
    left_on='drug_name',
    right_on='title',
    how='left'
)

# 5. Drop column
merged = merged.drop(columns=['title'])
merged

C:\Users\Asus\AppData\Local\Temp\ipykernel_22612\1384930884.py:2: DtypeWarning: Columns (30) have mixed types. Specify dtype option on import or set low_memory=False.
  drugbank_info = pd.read_csv("Data/drugbank_drugs_info.csv")

,drug_name,smiles,iupac,molecular_weight,synonyms,description_x,max_phase,drug_type,mechanism,target,description_y
0,succimer,NaN,NaN,NaN,NaN,NaN,4.0,Small molecule,Lead chelating agent,NaN,"Succimer (2,3-meso-dimercaptosuccinic acid) is..."
1,sargramostim,NaN,NaN,NaN,NaN,NaN,4.0,Protein,Granulocyte-macrophage colony-stimulating fact...,NaN,NaN
2,caffeine,NaN,NaN,NaN,NaN,NaN,4.0,Small molecule,Adenosine receptor antagonist,NaN,intra-arterial (brachial artery of non dominan...
3,apixaban,NaN,NaN,NaN,NaN,NaN,4.0,Small molecule,Coagulation factor X inhibitor,NaN,"Apixaban: Twice daily, 30 days\nPlacebo: Once ..."
4,ibrexafungerp,NaN,NaN,NaN,NaN,NaN,4.0,Small molecule,"1,3-beta-glucan synthase inhibitor",NaN,Ibrexafungerp 300 mg BID for 1 day
...,...,...,...,...,...,...,...,...,...,...,...
2186,porfiromycin,CC1=C(C(=O)C2=C(C1=O)N3CC4C(C3(C2COC(=O)N)OC)N...,"[(4S,6S,7R,8S)-11-amino-7-methoxy-5,12-dimethy...",348.35,Porfiromycin; 801-52-5; N-Methylmitomycin C; M...,NaN,3.0,Small molecule,NaN,NaN,NaN
2187,penciclovir,C1=NC2=C(N1CCC(CO)CO)N=C(NC2=O)N,2-amino-9-[4-hydroxy-3-(hydroxymethyl)butyl]-1...,253.26,penciclovir; 39809-25-1; Denavir; Pencicloviru...,NaN,4.0,Small molecule,Human herpesvirus 1 DNA polymerase inhibitor,NaN,Penciclovir every 2 hours during waking hours ...
2188,cinitapride,CCOC1=CC(=C(C=C1C(=O)NC2CCN(CC2)CC3CCC=CC3)[N+...,4-amino-N-[1-(cyclohex-3-en-1-ylmethyl)piperid...,402.50,Cinitapride; 66564-14-5; Paxapride; Cinitaprid...,NaN,3.0,Small molecule,NaN,NaN,"cinitapride 1 mg for each dose, 3 mg/daily, fo..."
2189,melagatran,C1CCC(CC1)C(C(=O)N2CCC2C(=O)NCC3=CC=C(C=C3)C(=...,2-[[(1R)-2-[(2S)-2-[(4-carbamimidoylphenyl)met...,429.50,Melagatran; 159776-70-2; Melagatran [INN]; UNI...,NaN,4.0,Small molecule,NaN,NaN,NaN
2190,pranlukast,C1=CC=C(C=C1)CCCCOC2=CC=C(C=C2)C(=O)NC3=CC=CC4...,N-[4-oxo-2-(2H-tetrazol-5-yl)chromen-8-yl]-4-(...,481.50,Pranlukast; 103177-37-3; Azlaire; Ono-1078; ON...,NaN,4.0,Small molecule,Cysteinyl leukotriene receptor 1 antagonist,NaN,NaN

In [58]:
merged.to_csv("druginfo_with_descriptions.csv", index=False)

In [59]:
merged = merged.drop(columns=['description_x'])

# 2. Rename description
merged = merged.rename(columns={'description_y': 'description'})

In [60]:
merged

,drug_name,smiles,iupac,molecular_weight,synonyms,max_phase,drug_type,mechanism,target,description
0,succimer,NaN,NaN,NaN,NaN,4.0,Small molecule,Lead chelating agent,NaN,"Succimer (2,3-meso-dimercaptosuccinic acid) is..."
1,sargramostim,NaN,NaN,NaN,NaN,4.0,Protein,Granulocyte-macrophage colony-stimulating fact...,NaN,NaN
2,caffeine,NaN,NaN,NaN,NaN,4.0,Small molecule,Adenosine receptor antagonist,NaN,intra-arterial (brachial artery of non dominan...
3,apixaban,NaN,NaN,NaN,NaN,4.0,Small molecule,Coagulation factor X inhibitor,NaN,"Apixaban: Twice daily, 30 days\nPlacebo: Once ..."
4,ibrexafungerp,NaN,NaN,NaN,NaN,4.0,Small molecule,"1,3-beta-glucan synthase inhibitor",NaN,Ibrexafungerp 300 mg BID for 1 day
...,...,...,...,...,...,...,...,...,...,...
2186,porfiromycin,CC1=C(C(=O)C2=C(C1=O)N3CC4C(C3(C2COC(=O)N)OC)N...,"[(4S,6S,7R,8S)-11-amino-7-methoxy-5,12-dimethy...",348.35,Porfiromycin; 801-52-5; N-Methylmitomycin C; M...,3.0,Small molecule,NaN,NaN,NaN
2187,penciclovir,C1=NC2=C(N1CCC(CO)CO)N=C(NC2=O)N,2-amino-9-[4-hydroxy-3-(hydroxymethyl)butyl]-1...,253.26,penciclovir; 39809-25-1; Denavir; Pencicloviru...,4.0,Small molecule,Human herpesvirus 1 DNA polymerase inhibitor,NaN,Penciclovir every 2 hours during waking hours ...
2188,cinitapride,CCOC1=CC(=C(C=C1C(=O)NC2CCN(CC2)CC3CCC=CC3)[N+...,4-amino-N-[1-(cyclohex-3-en-1-ylmethyl)piperid...,402.50,Cinitapride; 66564-14-5; Paxapride; Cinitaprid...,3.0,Small molecule,NaN,NaN,"cinitapride 1 mg for each dose, 3 mg/daily, fo..."
2189,melagatran,C1CCC(CC1)C(C(=O)N2CCC2C(=O)NCC3=CC=C(C=C3)C(=...,2-[[(1R)-2-[(2S)-2-[(4-carbamimidoylphenyl)met...,429.50,Melagatran; 159776-70-2; Melagatran [INN]; UNI...,4.0,Small molecule,NaN,NaN,NaN
2190,pranlukast,C1=CC=C(C=C1)CCCCOC2=CC=C(C=C2)C(=O)NC3=CC=CC4...,N-[4-oxo-2-(2H-tetrazol-5-yl)chromen-8-yl]-4-(...,481.50,Pranlukast; 103177-37-3; Azlaire; Ono-1078; ON...,4.0,Small molecule,Cysteinyl leukotriene receptor 1 antagonist,NaN,NaN

In [61]:
# 9. Merge back to trial data
df_merged = df_expanded.merge(merged, on='drug_name', how='left').drop_duplicates(subset=['nct_id', 'drug_name'])

def _is_number(val):
    try:
        float(val)
        return True
    except (ValueError, TypeError):
        return False
        
# 10. Collapse per trial
grouped = df_merged.groupby('nct_id').agg({
    'drug_name': lambda x: '; '.join(sorted(set(x.dropna()))),
    'smiles': lambda x: '; '.join(sorted(set(x.dropna()))),
    'description': lambda x: '; '.join(sorted(set(x.dropna()))),
    'iupac': lambda x: '; '.join(sorted(set(x.dropna()))),
    'molecular_weight': lambda x: '; '.join(
        str(round(float(v), 2)) for v in set(x.dropna()) if _is_number(v)
    ),
    'synonyms': lambda x: '; '.join(sorted(set(x.dropna()))),
    'max_phase': lambda x: '; '.join(str(p) for p in set(x.dropna())),
    'drug_type': lambda x: '; '.join(sorted(set(x.dropna()))),
    'mechanism': lambda x: '; '.join(sorted(set(x.dropna()))),
    'target': lambda x: '; '.join(sorted(set(x.dropna()))),
}).reset_index()

In [62]:
grouped

,nct_id,drug_name,smiles,description,iupac,molecular_weight,synonyms,max_phase,drug_type,mechanism,target
0,NCT00000114,vitamin e,CC1=C(C2=C(CCC(O2)(C)CCCC(C)CCCC(C)CCCC(C)C)C(...,,"(2R)-2,5,7,8-tetramethyl-2-[(4R,8R)-4,8,12-tri...",430.7,VITAMIN E; alpha-Tocopherol; 59-02-9; D-alpha-...,4.0,Unknown,,
1,NCT00000115,acetazolamide,CC(=O)NC1=NN=C(S1)S(=O)(=O)N,Subjects will begin with four 250 mg tablets d...,"N-(5-sulfamoyl-1,3,4-thiadiazol-2-yl)acetamide",222.3,acetazolamide; 59-66-5; Diamox; Acetamox; Neph...,4.0,Small molecule,Carbonic anhydrase I inhibitor,
2,NCT00000122,fluorouracil,C1=C(C(=O)NC(=O)N1)F,,"5-fluoro-1H-pyrimidine-2,4-dione",130.08,5-Fluorouracil; fluorouracil; 51-21-8; 5-FU; F...,4.0,Small molecule,Thymidylate synthase inhibitor,
3,NCT00000134,foscarnet; ganciclovir,C(=O)(O)P(=O)(O)O; C1=NC2=C(N1COC(CO)CO)N=C(NC...,"60 mg/kg every 8 hours, 90 mg/kg/day","2-amino-9-(1,3-dihydroxypropan-2-yloxymethyl)-...",126.01; 255.23,foscarnet; Phosphonoformic acid; Phosphonoform...,4.0,Small molecule,Human herpesvirus 1 DNA polymerase inhibitor,
4,NCT00000136,foscarnet; ganciclovir,C(=O)(O)P(=O)(O)O; C1=NC2=C(N1COC(CO)CO)N=C(NC...,"60 mg/kg every 8 hours, 90 mg/kg/day","2-amino-9-(1,3-dihydroxypropan-2-yloxymethyl)-...",126.01; 255.23,foscarnet; Phosphonoformic acid; Phosphonoform...,4.0,Small molecule,Human herpesvirus 1 DNA polymerase inhibitor,
...,...,...,...,...,...,...,...,...,...,...,...
61519,NCT06649409,eplerenone; fludrocortisone,CC12CCC(=O)C=C1CC(C3C24C(O4)CC5(C3CCC56CCC(=O)...,Fludrocortisone 0.2 mg by mouth daily for 30 d...,"(8S,9R,10S,11S,13S,14S,17R)-9-fluoro-11,17-dih...",380.4; 414.5,Eplerenone; Inspra; Epoxymexrenone; 107724-20-...,2.0; 4.0,Small molecule,Mineralocorticoid receptor antagonist,
61520,NCT06654531,dexmedetomidine,CC1=C(C(=CC=C1)C(C)C2=CN=CN2)C,,"5-[(1S)-1-(2,3-dimethylphenyl)ethyl]-1H-imidazole",200.28,DEXMEDETOMIDINE; 113775-47-6; Dexmedetomidina;...,4.0,Small molecule,,
61521,NCT06654570,letrozole,C1=CC(=CC=C1C#N)C(C2=CC=C(C=C2)C#N)N3C=NC=N3,Letrozole 2.5 mg by mouth daily for 24 weeks,"4-[(4-cyanophenyl)-(1,2,4-triazol-1-yl)methyl]...",285.3,"letrozole; 112809-51-5; Femara; 4,4'-((1h-1,2,...",4.0,Small molecule,Cytochrome P450 19A1 inhibitor,
61522,NCT06655818,dostarlimab,,,,,,4.0,Antibody,Programmed cell death protein 1 antagonist,
61523,NCT06657066,albuterol; beclomethasone; formoterol fumarate,CC(C)(C)NCC(C1=CC(=C(C=C1)O)CO)O; CC(CC1=CC=C(...,,"(8S,9R,10S,11S,13S,14S,16S,17R)-9-chloro-11,17...",408.9; 804.9; 239.31,Formoterol hemifumarate; 43229-80-7; FORMOTERO...,2.0; 4.0,Small molecule,Beta-2 adrenergic receptor agonist,

In [66]:
df = pd.read_csv("ctod_data.csv", low_memory=False)
trial_metadata = df.drop_duplicates(subset='nct_id')

# Merge metadata into your grouped dataset (1 row per nct_id)
grouped_enriched = grouped.merge(trial_metadata, on='nct_id', how='left')
grouped_enriched

,nct_id,drug_name,smiles,description,iupac,molecular_weight,synonyms,max_phase,drug_type,mechanism,...,healthy_volunteers,population,criteria,gender_description,gender_based,adult,child,older_adult,design,features
0,NCT00000114,vitamin e,CC1=C(C2=C(CCC(O2)(C)CCCC(C)CCCC(C)CCCC(C)C)C(...,,"(2R)-2,5,7,8-tetramethyl-2-[(4R,8R)-4,8,12-tri...",430.7,VITAMIN E; alpha-Tocopherol; 59-02-9; D-alpha-...,4.0,Unknown,,...,NaN,NaN,men and nonpregnant women between ages 18 and ...,NaN,NaN,t,f,f,randomized factorial treatment double,PHASE3 retinal diseases; eye diseases; eye dis...
1,NCT00000115,acetazolamide,CC(=O)NC1=NN=C(S1)S(=O)(=O)N,Subjects will begin with four 250 mg tablets d...,"N-(5-sulfamoyl-1,3,4-thiadiazol-2-yl)acetamide",222.3,acetazolamide; 59-66-5; Diamox; Acetamox; Neph...,4.0,Small molecule,Carbonic anhydrase I inhibitor,...,NaN,NaN,males and females 8 years of age or older and ...,NaN,NaN,t,t,t,randomized crossover treatment double,PHASE2 macular degeneration; retinal degenerat...
2,NCT00000122,fluorouracil,C1=C(C(=O)NC(=O)N1)F,,"5-fluoro-1H-pyrimidine-2,4-dione",130.08,5-Fluorouracil; fluorouracil; 51-21-8; 5-FU; F...,4.0,Small molecule,Thymidylate synthase inhibitor,...,f,NaN,men and women with uncontrolled intraocular pr...,NaN,NaN,t,t,t,randomized treatment double,PHASE3 ocular hypertension; eye diseases; glau...
3,NCT00000134,foscarnet; ganciclovir,C(=O)(O)P(=O)(O)O; C1=NC2=C(N1COC(CO)CO)N=C(NC...,"60 mg/kg every 8 hours, 90 mg/kg/day","2-amino-9-(1,3-dihydroxypropan-2-yloxymethyl)-...",126.01; 255.23,foscarnet; Phosphonoformic acid; Phosphonoform...,4.0,Small molecule,Human herpesvirus 1 DNA polymerase inhibitor,...,f,NaN,inclusion criteria: males and females eligible...,NaN,NaN,t,f,t,randomized factorial treatment double,PHASE3 blood-borne infections; communicable di...
4,NCT00000136,foscarnet; ganciclovir,C(=O)(O)P(=O)(O)O; C1=NC2=C(N1COC(CO)CO)N=C(NC...,"60 mg/kg every 8 hours, 90 mg/kg/day","2-amino-9-(1,3-dihydroxypropan-2-yloxymethyl)-...",126.01; 255.23,foscarnet; Phosphonoformic acid; Phosphonoform...,4.0,Small molecule,Human herpesvirus 1 DNA polymerase inhibitor,...,f,NaN,inclusion criteria:~* cmv retinitis in one or ...,NaN,NaN,t,t,t,randomized parallel treatment single,PHASE3 infections; virus diseases; retinal dis...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61519,NCT06649409,eplerenone; fludrocortisone,CC12CCC(=O)C=C1CC(C3C24C(O4)CC5(C3CCC56CCC(=O)...,Fludrocortisone 0.2 mg by mouth daily for 30 d...,"(8S,9R,10S,11S,13S,14S,17R)-9-fluoro-11,17-dih...",380.4; 414.5,Eplerenone; Inspra; Epoxymexrenone; 107724-20-...,2.0; 4.0,Small molecule,Mineralocorticoid receptor antagonist,...,t,NaN,inclusion criteria:~1. age of 18 to 55 years i...,NaN,NaN,t,f,f,randomized parallel other none,PHASE1 anti-inflammatory agents; antihyperten...
61520,NCT06654531,dexmedetomidine,CC1=C(C(=CC=C1)C(C)C2=CN=CN2)C,,"5-[(1S)-1-(2,3-dimethylphenyl)ethyl]-1H-imidazole",200.28,DEXMEDETOMIDINE; 113775-47-6; Dexmedetomidina;...,4.0,Small molecule,,...,f,NaN,inclusion criteria:~* asa physical status i-ii...,NaN,NaN,t,f,f,randomized parallel prevention none,PHASE2/PHASE3 adrenergic agents; adrenergic a...
61521,NCT06654570,letrozole,C1=CC(=CC=C1C#N)C(C2=CC=C(C=C2)C#N)N3C=NC=N3,Letrozole 2.5 mg by mouth daily for 24 weeks,"4-[(4-cyanophenyl)-(1,2,4-triazol-1-yl)methyl]...",285.3,"letrozole; 112809-51-5; Femara; 4,4'-((1h-1,2,...",4.0,Small molecule,Cytochrome P450 19A1 inhibitor,...,f,NaN,inclusion criteria:~* eligible patients were p...,Females,t,t,f,t,single_group treatment none,PHASE2 neoplasms by site; neoplasms; breast di...
61522,NCT06655818,dostarlimab,,,,,,4.0,Antibody,Programmed cell death protein 1 antagonist,...,f,NaN,inclusion criteria:~* participant must be 18 y...,NaN,NaN,t,f,t,single_group treatment none,PHASE1/PHASE2 neoplasms by histologic type; ne...
61523,NCT06657066,albuterol; beclomethasone; formoterol fumarate,CC(C)(C)NCC(C1=CC(=C(C=C1)O)CO)O; CC(CC1=CC=C(...,,"(8S,9R,10S,11S,13S,14S,16S,17R)-9-chloro-11,17...",408.9; 804.9; 239.31,Formoterol hemifumarate; 43229-80-7; FORMOTERO...,2.0; 4.0,Small molecule,Beta-2 adrenergic receptor agonist,...,f,NaN,inclusion criteria~1. patient of both genders ...,NaN,NaN,t,f,t,randomized parallel treatment double,PHASE2/PHASE3 bronchial diseases; respiratory ...

In [67]:
cols = ['nct_id'] + [col for col in grouped_enriched.columns if col != 'nct_id']
grouped_enriched = grouped_enriched[cols]
grouped_enriched

,nct_id,drug_name,smiles,description,iupac,molecular_weight,synonyms,max_phase,drug_type,mechanism,...,healthy_volunteers,population,criteria,gender_description,gender_based,adult,child,older_adult,design,features
0,NCT00000114,vitamin e,CC1=C(C2=C(CCC(O2)(C)CCCC(C)CCCC(C)CCCC(C)C)C(...,,"(2R)-2,5,7,8-tetramethyl-2-[(4R,8R)-4,8,12-tri...",430.7,VITAMIN E; alpha-Tocopherol; 59-02-9; D-alpha-...,4.0,Unknown,,...,NaN,NaN,men and nonpregnant women between ages 18 and ...,NaN,NaN,t,f,f,randomized factorial treatment double,PHASE3 retinal diseases; eye diseases; eye dis...
1,NCT00000115,acetazolamide,CC(=O)NC1=NN=C(S1)S(=O)(=O)N,Subjects will begin with four 250 mg tablets d...,"N-(5-sulfamoyl-1,3,4-thiadiazol-2-yl)acetamide",222.3,acetazolamide; 59-66-5; Diamox; Acetamox; Neph...,4.0,Small molecule,Carbonic anhydrase I inhibitor,...,NaN,NaN,males and females 8 years of age or older and ...,NaN,NaN,t,t,t,randomized crossover treatment double,PHASE2 macular degeneration; retinal degenerat...
2,NCT00000122,fluorouracil,C1=C(C(=O)NC(=O)N1)F,,"5-fluoro-1H-pyrimidine-2,4-dione",130.08,5-Fluorouracil; fluorouracil; 51-21-8; 5-FU; F...,4.0,Small molecule,Thymidylate synthase inhibitor,...,f,NaN,men and women with uncontrolled intraocular pr...,NaN,NaN,t,t,t,randomized treatment double,PHASE3 ocular hypertension; eye diseases; glau...
3,NCT00000134,foscarnet; ganciclovir,C(=O)(O)P(=O)(O)O; C1=NC2=C(N1COC(CO)CO)N=C(NC...,"60 mg/kg every 8 hours, 90 mg/kg/day","2-amino-9-(1,3-dihydroxypropan-2-yloxymethyl)-...",126.01; 255.23,foscarnet; Phosphonoformic acid; Phosphonoform...,4.0,Small molecule,Human herpesvirus 1 DNA polymerase inhibitor,...,f,NaN,inclusion criteria: males and females eligible...,NaN,NaN,t,f,t,randomized factorial treatment double,PHASE3 blood-borne infections; communicable di...
4,NCT00000136,foscarnet; ganciclovir,C(=O)(O)P(=O)(O)O; C1=NC2=C(N1COC(CO)CO)N=C(NC...,"60 mg/kg every 8 hours, 90 mg/kg/day","2-amino-9-(1,3-dihydroxypropan-2-yloxymethyl)-...",126.01; 255.23,foscarnet; Phosphonoformic acid; Phosphonoform...,4.0,Small molecule,Human herpesvirus 1 DNA polymerase inhibitor,...,f,NaN,inclusion criteria:~* cmv retinitis in one or ...,NaN,NaN,t,t,t,randomized parallel treatment single,PHASE3 infections; virus diseases; retinal dis...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61519,NCT06649409,eplerenone; fludrocortisone,CC12CCC(=O)C=C1CC(C3C24C(O4)CC5(C3CCC56CCC(=O)...,Fludrocortisone 0.2 mg by mouth daily for 30 d...,"(8S,9R,10S,11S,13S,14S,17R)-9-fluoro-11,17-dih...",380.4; 414.5,Eplerenone; Inspra; Epoxymexrenone; 107724-20-...,2.0; 4.0,Small molecule,Mineralocorticoid receptor antagonist,...,t,NaN,inclusion criteria:~1. age of 18 to 55 years i...,NaN,NaN,t,f,f,randomized parallel other none,PHASE1 anti-inflammatory agents; antihyperten...
61520,NCT06654531,dexmedetomidine,CC1=C(C(=CC=C1)C(C)C2=CN=CN2)C,,"5-[(1S)-1-(2,3-dimethylphenyl)ethyl]-1H-imidazole",200.28,DEXMEDETOMIDINE; 113775-47-6; Dexmedetomidina;...,4.0,Small molecule,,...,f,NaN,inclusion criteria:~* asa physical status i-ii...,NaN,NaN,t,f,f,randomized parallel prevention none,PHASE2/PHASE3 adrenergic agents; adrenergic a...
61521,NCT06654570,letrozole,C1=CC(=CC=C1C#N)C(C2=CC=C(C=C2)C#N)N3C=NC=N3,Letrozole 2.5 mg by mouth daily for 24 weeks,"4-[(4-cyanophenyl)-(1,2,4-triazol-1-yl)methyl]...",285.3,"letrozole; 112809-51-5; Femara; 4,4'-((1h-1,2,...",4.0,Small molecule,Cytochrome P450 19A1 inhibitor,...,f,NaN,inclusion criteria:~* eligible patients were p...,Females,t,t,f,t,single_group treatment none,PHASE2 neoplasms by site; neoplasms; breast di...
61522,NCT06655818,dostarlimab,,,,,,4.0,Antibody,Programmed cell death protein 1 antagonist,...,f,NaN,inclusion criteria:~* participant must be 18 y...,NaN,NaN,t,f,t,single_group treatment none,PHASE1/PHASE2 neoplasms by histologic type; ne...
61523,NCT06657066,albuterol; beclomethasone; formoterol fumarate,CC(C)(C)NCC(C1=CC(=C(C=C1)O)CO)O; CC(CC1=CC=C(...,,"(8S,9R,10S,11S,13S,14S,16S,17R)-9-chloro-11,17...",408.9; 804.9; 239.31,Formoterol hemifumarate; 43229-80-7; FORMOTERO...,2.0; 4.0,Small molecule,Beta-2 adrenergic receptor agonist,...,f,NaN,inclusion criteria~1. patient of both genders ...,NaN,NaN,t,f,t,randomized parallel treatment double,PHASE2/PHASE3 bronchial diseases; respiratory ...

In [68]:
grouped_enriched.to_csv("drugbank_info_smiles.csv", index=False)
print("SAVED")

SAVED